# Generated by Django 5.2 on 2025-05-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_review_rating_alter_shippingoption_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_deal',
            field=models.BooleanField(default=False),
        ),
    ]
